#!/bin/bash

[ -z "$BACKUP_DIR" ] && export BACKUP_DIR="/backup"
[ -z "$BACKUP_RSYNC" ] && export BACKUP_RSYNC="rsync -v --progress"

if [ $# -lt 2 ]; then
	echo "Usage: $0 <application name> <directory 1> [<directory 2>, ...]" >&2
	exit 1
fi

BACKUP_DIR="$BACKUP_DIR/$1"
shift
FILES="$*"

date_param=""
[ ! -z "$BACKUP_TIME" ] && date_param="-d$BACKUP_TIME"

THIS_BACKUP="$BACKUP_DIR/$(date "$date_param" +%Y-%m-%dT%H:%M:%S)/"
LAST_BACKUP_LINK="$BACKUP_DIR/last"
LAST_BACKUP_DIR="$LAST_BACKUP_LINK/"

test ! -e "$THIS_BACKUP" && ( mkdir -p "$THIS_BACKUP" || exit $? )

if [ -e "$LAST_BACKUP_DIR" ]; then
	$BACKUP_RSYNC '-aAHS' '--link-dest' "$LAST_BACKUP_DIR" $FILES "$THIS_BACKUP"
	ret=$?
else
	$BACKUP_RSYNC '-aAHS' $FILES "$THIS_BACKUP"
	ret=$?
fi

test ! $ret -eq 0 -a ! $ret -eq 24  && exit $ret

test -L "$LAST_BACKUP_LINK" && ( rm -f "$LAST_BACKUP_LINK" || exit $? )

ln -s "$THIS_BACKUP" "$LAST_BACKUP_LINK" || exit $?

exit 0
