#!/bin/bash

[ -z "$BACKUP_DIR" ] && export BACKUP_DIR="/backup"
[ -z "$BACKUP_RSYNC" ] && export BACKUP_RSYNC="rsync -zv --progress"
[ -z "$BACKUP_RSYNC_FLAGS" ] && export BACKUP_RSYNC_FLAGS="-AX"

if [ $# -lt 2 ]; then
	echo "Usage: $0 <application name> <directory 1> [<directory 2>, ...]" >&2
	exit 1
fi

BACKUP_DIR="$BACKUP_DIR/$1"
shift
FILES="$*"

date_param="date"
[ ! -z "$BACKUP_TIME" ] && date_param="date -d$BACKUP_TIME"

THIS_BACKUP="$BACKUP_DIR/$($date_param +%Y-%m-%dT%H:%M:%S)/"
LAST_BACKUP_LINK="$BACKUP_DIR/last"
LAST_BACKUP_DIR="$LAST_BACKUP_LINK/"

if [ -e "$THIS_BACKUP" ]; then
	echo "Backup directory $THIS_BACKUP already exists."
	exit 1
fi

mkdir -p "$THIS_BACKUP" || exit $?

if [ -e "$LAST_BACKUP_DIR" ]; then
	$BACKUP_RSYNC $BACKUP_RSYNC_FLAGS '-aHS' '--link-dest' "$LAST_BACKUP_DIR" $FILES "$THIS_BACKUP"
	ret=$?
else
	$BACKUP_RSYNC $BACKUP_RSYNC_FLAGS '-aHS' $FILES "$THIS_BACKUP"
	ret=$?
fi

if [ ! $ret -eq 0 -a ! $ret -eq 24 ]; then
	rm -rf "$THIS_BACKUP"
	exit $ret
fi

test -L "$LAST_BACKUP_LINK" && ( rm -f "$LAST_BACKUP_LINK" || exit $? )

ln -s "$THIS_BACKUP" "$LAST_BACKUP_LINK" || exit $?

exit 0
