#!/bin/bash
case "$1" in
	start)
		iptables -t nat -A OUTPUT -j REDSOCKS
	;;
	stop)
		iptables -t nat -L OUTPUT --line-numbers | grep REDSOCKS | cut -d' ' -f1 | sort -r --numeric | while read line; do
			iptables -t nat -D OUTPUT "$line"
		done
	;;
esac
