#!/usr/bin/php
<?php
	if($argc < 2)
	{
		fputs(STDERR, "Usage: ".$argv[0]." <cutlist file (in)> [edl file (out)]\n");
		exit(1);
	}

	$CUTLIST = $argv[1];
	$EDL = ($argc > 2 && $argv[2] != "/dev/stdout" && $argv[2] != "-") ? $argv[2] : false;

	if(!is_file($CUTLIST) || !is_readable($CUTLIST))
	{
		fputs(STDERR, "cutlist file is not readable.\n");
		exit(1);
	}

	if($EDL)
	{
		if(file_exists($EDL))
		{
			if(!is_file($EDL) || !is_writable($EDL))
			{
				fputs(STDERR, "EDL file is not writable.\n");
				exit(1);
			}

			fputs(STDOUT, "EDL file already exists. Overwrite? ");

			$answer = strtolower(trim(fgets(STDIN)));
			if(!in_array($answer, array("yes", "y", "ja", "j")))
			{
				fputs(STDERR, "Aborting.\n");
				exit(2);
			}
		}
		elseif(!is_writable(dirname($EDL)))
		{
			fputs(STDERR, "EDL file is not writable.\n");
			exit(1);
		}
	}

	$fh = ($EDL ? fopen($EDL, "w") : STDOUT);
	if(!$fh)
	{
		fputs(STDERR, "Could not open EDL file for writing.\n");
		exit(1);
	}

	$cutlist_content = readINIfile($CUTLIST, ";");
	if(!$cutlist_content)
	{
		fputs(STDERR, "cutlist parsing failed.\n");
		exit(1);
	}

	$cuts = null;
	if(isset($cutlist_content['general']) && isset($cutlist_content['general']['noofcuts']))
		$cuts = $cutlist_content['general']['noofcuts'];
	else
		$keys = array_keys($cutlist_content);

	$edl_output = array();
	$edl_i = 0;

	for($i=0; ($cuts === null) ? $i<count($keys) : $i<$cuts; $i++)
	{
		if($cuts === null)
		{
			$k = $keys[$i];
			if(substr($k, 0, 3) != "cut") continue;
		}
		else
		{
			$k = "cut".$i;
			if(!isset($cuts["cut".$i]))
			{
				fputs(STDERR, "Warning: Cut ".$i." does not exist.\n");
				continue;
			}
		}
		$v = &$cutlist_content[$k];

		if(!isset($v['start']) || (!isset($v['duration']) && !isset($v['end'])))
		{
			fputs(STDERR, "Warning: Invalid cut ".$i.".\n");
			continue;
		}

		if(!isset($v['end']))
			$v['end'] = $v['start'] + $v['duration'];

		if($edl_i == 0)
			$edl_output[$edl_i] = array(0);
		$edl_output[$edl_i][1] = $v['start'];
		$edl_output[++$edl_i] = array($v['end']);
	}

	if(count($edl_output) > 0)
		$edl_output[$edl_i][1] = 80000000;

	foreach($edl_output as $l)
	{
		if($l[0] == $l[1]) continue;
		fwrite($fh, $l[0]." ".$l[1]." 0\n");
	}

	fclose($fh);
	exit(0);

function readINIfile ($filename, $commentchar) {
  $array1 = file($filename);
  $section = '';
  for ($line_num = 0; $line_num <= sizeof($array1); $line_num++) {
   $filedata = $array1[$line_num];
   $dataline = trim($filedata);
   $firstchar = substr($dataline, 0, 1);
   if ($firstchar!=$commentchar && $dataline!='') {
     //It's an entry (not a comment and not a blank line)
     if ($firstchar == '[' && substr($dataline, -1, 1) == ']') {
       //It's a section
       $section = strtolower(substr($dataline, 1, -1));
     }else{
       //It's a key...
       $delimiter = strpos($dataline, '=');
       if ($delimiter > 0) {
         //...with a value
         $key = strtolower(trim(substr($dataline, 0, $delimiter)));
         $array2[$section][$key] = '';
         $value = trim(substr($dataline, $delimiter + 1));
         while (substr($value, -1, 1) == '\\') {
             //...value continues on the next line
             $value = substr($value, 0, strlen($value)-1);
             $array2[$section][$key] .= stripcslashes($value);
             $line_num++;
             $value = trim($array1[$line_num]);
         }
         $array2[$section][$key] .= stripcslashes($value);
         $array2[$section][$key] = trim($array2[$section][$key]);
         if (substr($array2[$section][$key], 0, 1) == '"' && substr($array2[$section][$key], -1, 1) == '"') {
            $array2[$section][$key] = substr($array2[$section][$key], 1, -1);
         }
       }else{
         //...without a value
         $array2[$section][strtolower(trim($dataline))]='';
       }
     }
   }else{
     //It's a comment or blank line.  Ignore.
   }
  }
  return $array2;
}
?>
