#!/usr/bin/php
<?php
	if($argc < 2)
	{
		fputs(STDERR, "Usage: ".$argv[0]." <cutlist file (in)> [avidemux file (out)]\n");
		exit(1);
	}

	$CUTLIST = $argv[1];
	$JS = ($argc > 2 && $argv[2] != "/dev/stdout" && $argv[2] != "-") ? $argv[2] : false;

	if(!is_file($CUTLIST) || !is_readable($CUTLIST))
	{
		fputs(STDERR, "cutlist file is not readable.\n");
		exit(1);
	}

	if($JS)
	{
		if(file_exists($JS))
		{
			if(!is_file($JS) || !is_writable($JS))
			{
				fputs(STDERR, "Avidemux file is not writable.\n");
				exit(1);
			}

			fputs(STDOUT, "Avidemux file already exists. Overwrite? ");

			$answer = strtolower(trim(fgets(STDIN)));
			if(!in_array($answer, array("yes", "y", "ja", "j")))
			{
				fputs(STDERR, "Aborting.\n");
				exit(2);
			}
		}
		elseif(!is_writable(dirname($JS)))
		{
			fputs(STDERR, "Avidemux file is not writable.\n");
			exit(1);
		}
	}

	$fh = ($JS ? fopen($JS, "w") : STDOUT);
	if(!$fh)
	{
		fputs(STDERR, "Could not open avidemux file for writing.\n");
		exit(1);
	}

	$cutlist_content = readINIfile($CUTLIST, ';');
	if(!$cutlist_content)
	{
		fputs(STDERR, "cutlist parsing failed.\n");
		exit(1);
	}

	$cuts = null;
	if(isset($cutlist_content['General']) && isset($cutlist_content['General']['NoOfCuts']))
		$cuts = $cutlist_content['General']['NoOfCuts'];
	else
		$keys = array_keys($cutlist_content);

	if(isset($argv[3])) $film = $argv[3];
	else $film = preg_replace("/\\.cutlist\$/", ".avi", $CUTLIST);

	fwrite($fh, "//AD  <- Needed to identify//\n");
	fwrite($fh, "var app = new Avidemux();\n");
	fwrite($fh, "app.load('".preg_replace("/[\\\\']/", "\\\\$0", $film)."');\n");
	fwrite($fh, "app.clearSegments();\n");

	for($i=0; ($cuts === null) ? $i<count($keys) : $i<$cuts; $i++)
	{
		if($cuts === null)
		{
			$k = $keys[$i];
			if(substr($k, 0, 3) != "Cut") continue;
		}
		else
		{
			$k = "Cut".$i;
			if(!isset($cuts["Cut".$i]))
			{
				fputs(STDERR, "Warning: Cut ".$i." does not exist.\n");
				continue;
			}
		}
		$v = &$cutlist_content[$k];

		if(!isset($v['Start']) || (!isset($v['Duration']) && !isset($v['End'])))
		{
			fputs(STDERR, "Warning: Invalid cut ".$i.".\n");
			continue;
		}

		if(!isset($v['End']))
			$v['End'] = $v['Start'] + $v['Duration'];

		fwrite($fh, "app.addSegment(0, ".round($v['Start']*25).", ".round($v['Duration']*25).");\n");
	}

	fwrite($fh, "app.video.setPostProc(3,3,0);\n");
	fwrite($fh, "app.video.setFps1000(25000);\n");
	fwrite($fh, "app.video.codec(\"Copy\",\"CQ=4\",\"0 \");\n");
	fwrite($fh, "app.audio.reset();\n");
	fwrite($fh, "app.audio.codec(\"copy\",128,0,\"\");\n");
	fwrite($fh, "app.audio.normalizeMode=0;\n");
	fwrite($fh, "app.audio.normalizeValue=0;\n");
	fwrite($fh, "app.audio.delay=0;\n");
	fwrite($fh, "app.audio.mixer(\"NONE\");\n");
	fwrite($fh, "app.audio.scanVBR();\n");
	fwrite($fh, "app.setContainer(\"AVI\");\n");
	fwrite($fh, "setSuccess(app.save('".preg_replace("/[\\\\']/", "\\\\$0", $film).".tmp'));\n");
	exit(0);

function readINIfile ($filename, $commentchar) {
  $array1 = file($filename);
  $section = '';
  for ($line_num = 0; $line_num <= sizeof($array1); $line_num++) {
   $filedata = $array1[$line_num];
   $dataline = trim($filedata);
   $firstchar = substr($dataline, 0, 1);
   if ($firstchar!=$commentchar && $dataline!='') {
     //It's an entry (not a comment and not a blank line)
     if ($firstchar == '[' && substr($dataline, -1, 1) == ']') {
       //It's a section
       $section = strtolower(substr($dataline, 1, -1));
     }else{
       //It's a key...
       $delimiter = strpos($dataline, '=');
       if ($delimiter > 0) {
         //...with a value
         $key = strtolower(trim(substr($dataline, 0, $delimiter)));
         $array2[$section][$key] = '';
         $value = trim(substr($dataline, $delimiter + 1));
         while (substr($value, -1, 1) == '\\') {
             //...value continues on the next line
             $value = substr($value, 0, strlen($value)-1);
             $array2[$section][$key] .= stripcslashes($value);
             $line_num++;
             $value = trim($array1[$line_num]);
         }
         $array2[$section][$key] .= stripcslashes($value);
         $array2[$section][$key] = trim($array2[$section][$key]);
         if (substr($array2[$section][$key], 0, 1) == '"' && substr($array2[$section][$key], -1, 1) == '"') {
            $array2[$section][$key] = substr($array2[$section][$key], 1, -1);
         }
       }else{
         //...without a value
         $array2[$section][strtolower(trim($dataline))]='';
       }
     }
   }else{
     //It's a comment or blank line.  Ignore.
   }
  }
  return $array2;
}
?>
