#!/usr/bin/php
<?php
	$ask = !isset($_ENV["cutlist_ask"]) || in_array(strtolower($_ENV["cutlist_ask"]), array("y", "yes"));

	if($argc < 2)
	{
		fputs(STDERR, "Usage: ".$argv[0]." <filename>\n");
		exit(1);
	}

	$fname = $argv[1];
	if(!is_file($fname))
	{
		fputs(STDERR, "File does not exist.\n");
		exit(1);
	}

	$url = "http://cutlist.de/getxml.php?version=0.9.8.0&ofsb=".filesize($fname);
	$tmp = "/tmp/cutlists.xml.".time();
	$cl = preg_replace("/\.(wmv|avi)(\.otrkey)?$/", ".cutlist", $fname);

	passthru("wget ".escapeshellarg($url)." -O ".escapeshellarg($tmp));

	if(filesize($tmp) < 1)
	{
		fputs(STDERR, "No cutlists have been found.\n");
		exit(2);
	}


	$dom = new DOMDocument();
	$dom->load($tmp);

	unlink($tmp);

	$cutlists = $dom->getElementsByTagName("cutlist");
	if($cutlists->length < 1)
	{
		fputs(STDERR, "No cutlists have been found.\n");
		exit(2);
	}

	$c = array();
	$best = null;

	for($i=0; $i<$cutlists->length; $i++)
	{
		$item = $cutlists->item($i);
		$c[$i+1] = $item->getElementsByTagName("id")->item(0)->firstChild->data;
		$rating_author = $item->getElementsByTagName("ratingbyauthor")->item(0)->firstChild->data;
		$rating_users = $item->getElementsByTagName("rating")->item(0)->firstChild->data;
		$title = $item->getElementsByTagName("name")->item(0)->firstChild->data;
		if(preg_match("/^".preg_quote(preg_replace("/(\\.(otrkey|avi|wmv))?$/", "", $fname), "/")."(\\.\\d+)*\\.cutlist\$/i", $title))
		{
			if(strlen($rating_users) == 0)
				$rating = $rating_author-1.25;
			else
				$rating = ($rating_author+$rating_users)/2;
			if(!$best || $rating > $best[1])
				$best = array($i+1, $rating);
		}
		if($ask)
			fputs(STDOUT, " (".($i+1).") ".$title." (rating ".$rating_users.", author rating ".$rating_author.")\n");
	}

	if($ask)
	{
		do
		{
			fputs(STDOUT, "\nEnter the number of the cutlist to download");
			if($best)
				fputs(STDOUT, " (suggestion: ".$best[0].")");
			fputs(STDOUT, ": ");
			$n = trim(fgets(STDIN));
		}
		while(!isset($c[$n]));
	}
	elseif($best)
		$n = $best[0];
	else
	{
		fputs(STDERR, "No cutlist could be selected.\n");
		exit(3);
	}

	$url = "http://cutlist.de/getfile.php?id=".$c[$n];
	passthru("wget ".escapeshellarg($url)." -O ".escapeshellarg($cl));

	$exit = 0;
	fputs(STDOUT, "Now cut? ".(isset($_ENV["ask"]) ? $_ENV["ask"]."\n" : ""));
	if(in_array(strtolower(trim(isset($_ENV["ask"]) ? $_ENV["ask"] : fgets(STDIN))), array("y", "yes")))
	{
		fputs(STDOUT, "\n");
		passthru("otrcut ".escapeshellarg($fname), $exit);
	}
	exit($exit);
?>
