#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <avi file>" >&2
	exit 1
fi

fname_avi="${1}"
fname_p="${fname_avi%.*}"
fname_mkv="${fname_p}.mkv"
fname_cutlist="${fname_p}.cutlist"
fname_edl="${fname_p}.edl"
fname_js="${fname_p}.avidemux.js"
fname_tmp="${fname_avi}.tmp"

if [ ! -z "$DISPLAY" ]; then
	if which avidemux2_qt4 >/dev/null 2>/dev/null; then
		avidemux="avidemux2_qt4"
	elif which avidemux2_gtk >/dev/null 2>/dev/null; then
		avidemux="avidemux2_gtk"
	elif which avidemux2 >/dev/null 2>/dev/null; then
		avidemux="avidemux2"
	elif which avidemux >/dev/null 2>/dev/null; then
		avidemux="avidemux"
	else
		avidemux="avidemux2_cli"
	fi
else
	avidemux="avidemux2_cli"
fi

[ -z "$otrcut_rm" ] && export otrcut_rm="rm -i"

[ ! -f "${fname_js}" -a -f "${fname_cutlist}" ] && ( cutlist2avidemux "${fname_cutlist}" "${fname_js}" "${fname_avi}" || exit $? )

ad_ret=1
if [ -f "${fname_js}" ]; then
	echo "Cutting..."
	"$avidemux" --nogui --force-smart --run "$fname_js" --quit
	ad_ret=${PIPESTATUS[0]}
	[[ "$ad_ret" = 0 ]] && echo "Finished" || echo "Failed"
elif [ ! -f "${fname_js}" -a ! -z "$DISPLAY" ]; then
	"$avidemux" "${fname_avi}"
	ad_ret=$?
fi
if [[ "$ad_ret" = 0 ]] && ( ( [[ "${fname_avi}" = "${fname_mkv}" ]] && [ -f "${fname_mkv}.tmp" ] ) || ( [[ "${fname_avi}" != "${fname_mkv}" ]] && [ -f "${fname_mkv}" ] ) )
then
	$otrcut_rm "${fname_avi}"
	if [ "${fname_avi}" = "${fname_mkv}" ]; then
		mv "${$fname_mkv}.tmp" "${fname_mkv}"
	fi
	[ -f "${fname_edl}" ] && $otrcut_rm "${fname_edl}"
	[ -f "${fname_js}" ] && $otrcut_rm "${fname_js}"
	[ -f "${fname_cutlist}" ] && $otrcut_rm "${fname_cutlist}"
fi
