#!/bin/bash

fname_cutlist="$(echo -n "$1" | sed -e 's/\.[a-zA-Z0-9]\+$//').cutlist"
fname_edl="$(echo -n "$1" | sed -e 's/\.[a-zA-Z0-9]\+$//').edl"

if [ ! -e "$fname_edl" -a -e "$fname_cutlist" ]; then
	cutlist2edl "$fname_cutlist" "$fname_edl"
fi

if [ -e "$fname_edl" ]; then
	mplayer -edl "$fname_edl" "$@"
else
	mplayer "$@"
fi
