#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <input audio file> [output ogg file]" >&2
	exit 1
fi

tmp_dir="/tmp/audio2ogg-$USER"

[ ! -d "$tmp_dir" ] && mkdir -p "$tmp_dir"

in="$1"

if [ ! -z "$2" ]; then
	out="$2"
else
	out="${in%.*}.ogg"
fi

[ -z "$audio2ogg_rm" ] && export audio2ogg_rm="rm -i"

tmp_template="$tmp_dir/$(date +%s)"

end() {
	sleep 1
	if [ "$(jobs | grep -c 'Running')" -gt 0 ]; then
		cat "$tmp" > /dev/null
	fi
	rm -f "$tmp" "$tmp_template.mp3" "$tmp_template.ogg"
	exit "$1"
}

trap 'end 1' 1 2 3 15

if [ -f "$in" ]; then
	mime="$(file -bi "$in")"
	if [[ "$mime" = "audio/mpeg" ]]; then
		ln -s "$in" "$tmp_template.mp3"
		mp32ogg "$tmp_template.mp3" || end $?
		mv "$tmp_template.ogg" "$out"
		end $?
	elif [[ "$mime" = "application/ogg" ]]; then
		cp "$in" "$out"
		end $?
	fi
fi

tmp="$tmp_template.wav"
mkfifo "$tmp"

mplayer -noconsolecontrols -ao "pcm:file=$tmp" -vo null "$in" >/dev/null 2>/dev/null &

oggenc "$tmp" -o "$out" && $audio2ogg_rm "$in"
end $?
