#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <input ogg file> [output mka file]" >&2
	exit 1
fi

in="$1"
if [ ! -z "$2" ]; then
	out="$2"
else
	out="${in%.ogg}.mka"
fi

[ -z "$ogg2mka_rm" ] && export ogg2mka_rm="rm -i"

mkvmerge -o "$out" -a 0 -D -S "$in" --track-order 0:0 && $ogg2mka_rm "$in"
