#!/bin/bash

if [ -z "$1" ]; then
	echo "Usage: $0 <input video file> [output avi file]" >&2
	exit 1
fi

in="$1"
if [ ! -z "$2" ]; then
	if [ -d "$2" ]; then
		out="$2/${in%.*}.mp4"
	else
		out="$2"
	fi
else
	out="${in%.*}.mp4"
fi

[ -z "$video2mobile_rm" ] && export video2mobile_rm="rm -i"

OUT_WIDTH=176
OUT_HEIGHT=144

OUT_ASPECT="$(echo "scale=3; $OUT_WIDTH/$OUT_HEIGHT" | bc)"

info="$(ffmpeg -i "$in" 2>&1)"
width="$(echo "$info" | grep -m1 Video: | perl -pe 's/^.* (\d+)x(\d+)([, ].*)?$/$1/')"
height="$(echo "$info" | grep -m1 Video: | perl -pe 's/^.* (\d+)x(\d+)([, ].*)?$/$2/')"
aspect="$(echo "scale=3; $width/$height" | bc)"

new_width=$OUT_WIDTH
new_height=$OUT_HEIGHT
padding_ap=""

if expr "$aspect" '<' "$OUT_ASPECT" >/dev/null; then
	new_width="$(echo $OUT_HEIGHT*$aspect | bc)"
elif expr "$aspect" '>' "$OUT_ASPECT" >/dev/null; then
	new_height="$(echo $OUT_WIDTH/$aspect | bc)"
fi

x="$(echo "($OUT_WIDTH-$new_width)/2" | bc)"
y="$(echo "($OUT_HEIGHT-$new_height)/2" | bc)"

ffmpeg -i "$in" -r 15 -b:a 64k -acodec aac -b:v 95k -vcodec mpeg4 -strict experimental -aspect "$OUT_ASPECT" -vf "scale=${new_width}x${new_height},pad=$OUT_WIDTH:$OUT_HEIGHT:$x:$y" "$out"
