#!/bin/bash

get_video_urls()
{
	episode="${1}"

	listing="$(wget -O- -o/dev/null "http://tvtotal.prosieben.de/tvtotal/includes/php/ajax.php?action=getSendungById&contentType=video&showId=${episode}-00&teaserType=video&tabbing=sendung")"

	date="$(echo "$listing" | grep 'related_linktext_headright' | head -1 | cut -d '>' -f2 | cut -d '<' -f1 | sed -e 's/\./\t/g')"
	day="$(echo "${date}" | cut -f1)"
	month="$(echo "${date}" | cut -f2)"
	year="$(echo "${date}" | cut -f3)"

	parts="$(echo "${listing}" | grep '<img' | cut -d'_' -f7 | cut -d'.' -f1)"
	echo "${parts}" | while read it; do
		echo -e "${it}\thttp://c11021-o.l.core.cdn.streamfarm.net/11021brainpool/ondemand/3583brainpool/tvtotal/${year}/${month}/${day}/${year}${month}${day}_tvttd${episode}_${it}.flv"
	done
}

get_playlist_from_cache()
{
	episode="${1}"

	dir="${HOME}/.tvtotal"
	[ ! -e "$dir" ] && mkdir -p "$dir"

	fname="${dir}/${episode}"
	if [ -e "$fname" ]; then
		cat "$fname"
	else
		playlist="$(get_video_urls "${episode}")"
		echo "$playlist" > "${fname}"
		echo "$playlist"
	fi
}

get_url_from_cache()
{
	episode="${1}"
	part="${2}"

	playlist="$(get_playlist_from_cache "$episode")"
	if [[ "$part" = "" ]]; then
		echo "$playlist" | cut -f2
	else
		echo "$playlist" | while read it; do
			if [[ "$(echo "$it" | cut -f1)" = "${part}" ]]; then
				echo "$it" | cut -f2
				break
			fi
		done
	fi
}

tidy_episode()
{
	episode="${1}"

	episode_length=`echo $episode | awk '{ print length($0); }'`

	while [[ $episode_length < 4 ]]; do
		episode='0'$episode
		episode_length=$[$episode_length+1]
	done
	echo "$episode"
}

tidy_part()
{
	part="${1}"

	if [[ "$part" = "" ]]; then
		return 0
	fi

	part_length=`echo $part | awk '{ print length($0); }'`
	while [[ $part_length < 2 ]]; do
		part='0'$part
		part_length=$[$part_length+1]
	done
	echo "$part"
}

if [[ $# < 1 ]]; then
	echo "Usage: $0 <episode> [part]" >&2
	exit 1
fi

episode="$(tidy_episode "${1}")"
part="$(tidy_part "${2}")"

urls="$(get_url_from_cache "$episode" "$part")"
if [[ "$urls" = "" ]]; then
	exit 1
fi

echo "$urls"
exit 0
